from collections import defaultdict
import sys
import re

def is_number(char):
    return char >= '0' and char <= '9'

def day_4_1():
    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        sum = 0

        for line in file:
            text = line.strip()
            match = re.search(r"Card\s+(\d+): (.*)", text)
            card_num = int(match.group(1))
            winning_nums_str, ticket_str = match.group(2).split(' | ')
            winning_nums = winning_nums_str.split()
            ticket = ticket_str.split()

            matches = 0
            for winning_num in winning_nums:
                if winning_num in ticket:
                    matches += 1
            print(f"card {card_num} has {matches} match(es)")

            if matches:
                sum += 2 ** (matches - 1)

        print(sum)


def day_4_2():
    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        # sum = 0
        cards = {}
        num_cards = defaultdict(lambda: 1)

        for line in file:
            text = line.strip()
            match = re.search(r"Card\s+(\d+): (.*)", text)
            card_num = int(match.group(1))

            winning_nums_str, ticket_str = match.group(2).split(' | ')
            winning_nums = winning_nums_str.split()
            ticket = ticket_str.split()

            cards[card_num] = (winning_nums, ticket)

        for i in range(len(cards), 0, -1):
            winning_nums, ticket = cards[i]

            matches = 0
            for winning_num in winning_nums:
                if winning_num in ticket:
                    matches += 1
            # print(f"card {i} has {matches} match(es)")

            if matches:
                for m in range(1, matches + 1):
                    # print(f"adding {i + m} to card {i}")
                    num_cards[i] += num_cards[i + m]

        # after computing the number of cards generated by having
        # one of each card, we start with one of each card in our problem
        print(sum(num_cards[i] for i in range(1, len(cards) + 1)))

day_4_2()
